"""adiciona tabela mensagens (log de conversas WhatsApp)

Revision ID: 0617e8654ab6
Revises: a1b2c3d4e5f6
Create Date: 2026-08-06 18:45:49.832971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0617e8654ab6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('remetente', sa.Enum('CLIENTE', 'ROBO', 'EQUIPE', name='remetente_mensagem'), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTA: o autogenerate do Alembic queria dropar o índice
    # uq_agendamento_tenant_horario_ativo (criado via SQL puro na migration
    # a1b2c3d4e5f6, não reflete no metadata do SQLAlchemy) — removido
    # propositalmente daqui, ele continua existindo no banco.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens')
    # ### end Alembic commands ###
