"""Adiciona conversa_estados para pausar o robo por conversa

Revision ID: 0bf5e218bba9
Revises: dd2b833f0a13
Create Date: 2026-08-11 22:07:19.042161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf5e218bba9'
down_revision = 'dd2b833f0a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversa_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('modo', sa.Enum('BOT', 'HUMANO', 'ENCERRADA', name='modo_conversa'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'telefone', name='uq_conversa_estado_tenant_telefone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversa_estados')
    # ### end Alembic commands ###
