"""remove modulo caixa fisico (abrir/fechar/sangria)

Revision ID: 2034fb0fd33d
Revises: 7da26200c46a
Create Date: 2026-08-17 21:42:29.453068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2034fb0fd33d'
down_revision = '7da26200c46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: o autogenerate também detectou (falso positivo) a remoção do
    # índice uq_agendamento_tenant_horario_ativo, que protege contra
    # agendamento duplicado (migration a1b2c3d4e5f6) — não tem nada a ver
    # com a remoção do Caixa, removido manualmente daqui de propósito.
    op.drop_table('caixa_movimentos')
    op.drop_table('caixas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixa_movimentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caixa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('valor', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], name=op.f('caixa_movimentos_caixa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('caixa_movimentos_pkey'))
    )
    op.create_table('caixas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('saldo_abertura', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('saldo_fechamento', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('aberto_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fechado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('caixas_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('caixas_pkey')),
    sa.UniqueConstraint('tenant_id', 'data', name=op.f('uq_caixa_tenant_data'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
