"""Adiciona modulo financeiro (contas, plano de contas, lancamentos, contas a pagar, caixa)

Revision ID: 7da26200c46a
Revises: 0bf5e218bba9
Create Date: 2026-08-11 22:12:59.256209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da26200c46a'
down_revision = '0bf5e218bba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('saldo_abertura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_fechamento', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aberto_em', sa.DateTime(), nullable=True),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'data', name='uq_caixa_tenant_data')
    )
    op.create_table('contas_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_de_contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('grupo', sa.Enum('RECEITA', 'CUSTO_VARIAVEL', 'DESPESA_FIXA', 'OUTRAS_RECEITAS', 'OUTRAS_DESPESAS', name='grupo_dre'), nullable=False),
    sa.Column('nota', sa.String(length=160), nullable=True),
    sa.Column('sistema', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caixa_movimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=160), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('recorrente_mensal', sa.Boolean(), nullable=False),
    sa.Column('parcela_atual', sa.Integer(), nullable=True),
    sa.Column('parcelas_total', sa.Integer(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['plano_de_contas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos_financeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipo_lancamento'), nullable=False),
    sa.Column('forma', sa.Enum('DINHEIRO', 'PIX', 'CREDITO', 'DEBITO', 'OUTRO', name='forma_pagamento'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=160), nullable=False),
    sa.Column('origem', sa.Enum('MANUAL', 'AGENDAMENTO', 'CONTA_PAGAR', name='origem_lancamento'), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['plano_de_contas.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas_financeiras.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos_financeiros')
    op.drop_table('contas_pagar')
    op.drop_table('caixa_movimentos')
    op.drop_table('plano_de_contas')
    op.drop_table('contas_financeiras')
    op.drop_table('caixas')
    # ### end Alembic commands ###
